/* BusKey 映射表 */
export default {
  // 经销销售订单: 'XSDD',
  // 销售报价: 'XSBJ',
  // 商机: 'SJ',
  // 产品销售出库: 'XSCK',
  // 采购申请: 'CGSQ',
  // 采购订单: 'CGDD',
  // 采购入库: 'CGRK',
  // 存货: 'CH',
  // 库存盘点: 'KCPD',
  // 本地库存调拨: 'BDKCDB',
  // 项目费用报销: 'FYBX',
  // 往来余额: 'WLYE',
  // 货币资金: 'HBZJ',
  // 项目立项: 'XMLX',
  // 项目计划: 'XMJH',
  // 项目任务: 'XMRW'
  OPPT : '商机',
  QUOT : '产品报价',
  SO : "经销销售订单",
  SO1 : "经销销售订单",
  PAPP : '采购申请',
  PO : '采购订单',
  POPI : '采购入库',
  SODL : '产品销售出库',
  REIM1 : '项目费用报销',
  PINI : '项目立项',
  PPLN : '项目计划',
  PTSK : '项目任务',
  TRAN : '本地库存调拨',
  STCK :'库存盘点'
}
